
import { Button } from "@/components/ui/button";

const Developers = () => {
  const features = [
    {
      icon: "🔒",
      title: "Works with Private Repos",
      description: "Scan your private GitHub repos securely with token auth",
      highlight: true,
    },
    {
      icon: "⚡",
      title: "Lightning-Fast Scans",
      description: "Run full AI scans in seconds right from the dashboard",
      highlight: false,
    },
    {
      icon: "🎯",
      title: "AI Security Reports",
      description: "Get clean, actionable reports generated by AI",
      highlight: false,
    },
    {
      icon: "🚫",
      title: "No SDKs Required",
      description: "Nothing to install. Just connect and scan.",
      highlight: false,
    },
    {
      icon: "🔧",
      title: "API Access Coming Soon",
      description: "Programmatic access to integrate scans into CI",
      highlight: false,
    },
    {
      icon: "💬",
      title: "Dev Community Support",
      description: "Join the Discord to get help and give feedback",
      highlight: false,
    },
  ];

  return (
    <section className="py-20 relative" id="developers">
      <div className="container mx-auto px-6">
        {/* CTA Section */}
        <div className="text-center mb-20">
          <h2 className="text-4xl md:text-6xl font-bold mb-8">
            Code secure. Stay secure. Let VibeSec do the hard work{" "}
            <span className="text-gray-400">you build confidently</span>.
          </h2>
          
          <Button 
            size="lg" 
            className="shine-effect bg-black border border-gray-600 text-white hover:bg-white/10 hover:border-gray-500 px-8 py-4 text-lg rounded-full transition-all duration-300 transform hover:scale-105"
          >
            Start Your First Scan ↗
          </Button>
        </div>

        {/* Developer Features */}
        <div className="max-w-6xl mx-auto px-6 relative z-10">
        <div className="text-center mb-16">
          <div className="inline-flex items-center px-3 py-1 glass-effect rounded-full mb-6 shiny-border">
            <span className="w-2 h-2 bg-white rounded-full mr-2 shadow-[0_0_10px_rgba(255,255,255,0.8)]"></span>
            <span className="text-white text-sm font-medium glow-text">FOR DEVELOPERS</span>
          </div>
          
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Built for Developers Who{" "}
            <span className="text-gray-400">Care About Security</span>
          </h2>
          
          <p className="text-xl text-gray-300 max-w-4xl mb-12">
            VibeSec integrates directly into your development workflow to catch vulnerabilities early. 
            Scan repos, get actionable insights, and ship confidently no security team required.
          </p>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <div 
                key={index}
                className={`p-6 rounded-xl border transition-all duration-300 hover:transform hover:scale-105 ${
                  feature.highlight 
                    ? 'bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-500/30' 
                    : 'bg-gray-900/50 border-gray-800 hover:border-gray-700'
                }`}
              >
                <div className="text-3xl mb-4">{feature.icon}</div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-gray-400 text-sm">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Community Section */}
        <div className="text-center">
          <h3 className="text-2xl font-bold mb-4">
            Join 100+ developers already using VibeSec to secure their codebase.
          </h3>
          
          <Button 
            size="lg" 
            variant="outline"
            className="shine-effect bg-black border border-gray-600 text-white hover:bg-white/10 hover:text-white hover:border-gray-500 rounded-full transition-all duration-300 transform hover:scale-105"
          >
            Start Free Trial ↗
          </Button>
        </div>
      </div>
    </section>
  );
};

export default Developers;
