
import { Button } from "@/components/ui/button";
import { Lock, Zap, Brain, Wrench, Shield, Code } from "lucide-react";

const Developers = () => {
  const features = [
    {
      icon: <Lock className="w-8 h-8" />,
      title: "Works with Private Repos",
      description: "Scan your private GitHub repos securely with token auth",
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: "Lightning-Fast Scans", 
      description: "Run full AI scans in seconds right from the dashboard",
    },
    {
      icon: <Brain className="w-8 h-8" />,
      title: "AI Security Reports",
      description: "Get clean, actionable reports generated by AI",
    },
    {
      icon: <Wrench className="w-8 h-8" />,
      title: "No SDKs Required",
      description: "Nothing to install. Just connect and scan.",
    },
    {
      icon: <Code className="w-8 h-8" />,
      title: "API Access Coming Soon",
      description: "Programmatic access to integrate scans into CI",
    },
    {
      icon: <Shield className="w-8 h-8" />,
      title: "Vulnerability Tracking", 
      description: "Track and monitor security issues across all your projects",
    },
  ];

  return (
    <section className="py-20 relative" id="developers">
      <div className="container mx-auto px-6">
        <div className="max-w-6xl mx-auto relative z-10">
          <div className="text-center mb-16">
            <div className="inline-flex items-center px-3 py-1 glass-effect rounded-full mb-6 shiny-border">
              <span className="w-2 h-2 bg-white rounded-full mr-2 shadow-[0_0_10px_rgba(255,255,255,0.8)]"></span>
              <span className="text-white text-sm font-medium glow-text">FOR DEVELOPERS</span>
            </div>
            
            <h2 className="text-4xl md:text-5xl font-bold mb-6" style={{ textShadow: '0 0 20px rgba(255,255,255,0.6), 0 0 40px rgba(255,255,255,0.4)' }}>
              Built for Developers Who{" "}
              <span className="text-gray-400">Care About Security</span>
            </h2>
            
            <p className="text-xl text-gray-300 max-w-4xl mx-auto mb-12">
              Censorly integrates directly into your development workflow to catch vulnerabilities early. 
              Scan repos, get actionable insights, and ship confidently no security team required.
            </p>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
              {features.map((feature, index) => (
                <div 
                  key={index}
                  className="group p-8 bg-black border-l-2 border-r-2 border-t-2 border-white/60 hover:border-white/80 transition-all duration-300 hover:transform hover:scale-105 relative overflow-hidden rounded-t-lg shadow-[0_0_20px_rgba(255,255,255,0.1)] hover:shadow-[0_0_30px_rgba(255,255,255,0.2)]"
                >
                  <div className="text-center">
                    <div className="flex justify-center mb-4 text-white">
                      {feature.icon}
                    </div>
                    <h3 className="text-xl font-semibold mb-3 text-white">{feature.title}</h3>
                    <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
                  </div>
                  
                  {/* Subtle hover effect */}
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"></div>
                </div>
              ))}
            </div>
          </div>

          {/* Community Section */}
          <div className="text-center">
            <h3 className="text-2xl font-bold mb-4">
              Join 100+ developers already using Censorly to secure their codebase.
            </h3>
            
            <Button 
              size="lg" 
              variant="outline"
              className="shine-effect bg-black border border-gray-600 text-white hover:bg-white/10 hover:text-white hover:border-gray-500 rounded-full transition-all duration-300 transform hover:scale-105"
            >
              Start Free Trial ↗
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Developers;
