
import { Button } from "@/components/ui/button";
import { Lock, Zap, Brain, Wrench, Chat } from "lucide-react";

const Developers = () => {
  const features = [
    {
      icon: <Lock className="w-6 h-6" />,
      title: "Works with Private Repos",
      description: "Scan your private GitHub repos securely with token auth",
      highlight: true,
    },
    {
      icon: <Zap className="w-6 h-6" />,
      title: "Lightning-Fast Scans",
      description: "Run full AI scans in seconds right from the dashboard",
      highlight: false,
    },
    {
      icon: <Brain className="w-6 h-6" />,
      title: "AI Security Reports",
      description: "Get clean, actionable reports generated by AI",
      highlight: false,
    },
    {
      icon: <Wrench className="w-6 h-6" />,
      title: "No SDKs Required",
      description: "Nothing to install. Just connect and scan.",
      highlight: false,
    },
    {
      icon: <Wrench className="w-6 h-6" />,
      title: "API Access Coming Soon",
      description: "Programmatic access to integrate scans into CI",
      highlight: false,
    },
    {
      icon: <Chat className="w-6 h-6" />,
      title: "Dev Community Support",
      description: "Join the Discord to get help and give feedback",
      highlight: false,
    },
  ];

  return (
    <section className="py-20 relative" id="developers">
      <div className="container mx-auto px-6">
        <div className="max-w-6xl mx-auto relative z-10">
          <div className="text-center mb-16">
            <div className="inline-flex items-center px-3 py-1 glass-effect rounded-full mb-6 shiny-border">
              <span className="w-2 h-2 bg-white rounded-full mr-2 shadow-[0_0_10px_rgba(255,255,255,0.8)]"></span>
              <span className="text-white text-sm font-medium glow-text">FOR DEVELOPERS</span>
            </div>
            
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Built for Developers Who{" "}
              <span className="text-gray-400">Care About Security</span>
            </h2>
            
            <p className="text-xl text-gray-300 max-w-4xl mx-auto mb-12">
              VibeSec integrates directly into your development workflow to catch vulnerabilities early. 
              Scan repos, get actionable insights, and ship confidently no security team required.
            </p>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
              {features.map((feature, index) => (
                <div 
                  key={index}
                  className="group p-6 rounded-2xl border border-gray-700 bg-black/50 hover:border-gray-600 transition-all duration-300 hover:transform hover:scale-105 relative overflow-hidden"
                >
                  <div className="flex items-start space-x-4">
                    <div className="flex-shrink-0 text-white">
                      {feature.icon}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold mb-2 text-white">{feature.title}</h3>
                      <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
                    </div>
                  </div>
                  
                  {/* Subtle hover effect */}
                  <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"></div>
                </div>
              ))}
            </div>
          </div>

          {/* Community Section */}
          <div className="text-center">
            <h3 className="text-2xl font-bold mb-4">
              Join 100+ developers already using VibeSec to secure their codebase.
            </h3>
            
            <Button 
              size="lg" 
              variant="outline"
              className="shine-effect bg-black border border-gray-600 text-white hover:bg-white/10 hover:text-white hover:border-gray-500 rounded-full transition-all duration-300 transform hover:scale-105"
            >
              Start Free Trial ↗
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Developers;
