
import { Button } from "@/components/ui/button";

const Features = () => {
  return (
    <section className="py-20">
      <div className="container mx-auto px-6">
        {/* Solutions Section */}
        <div className="mt-20">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center px-3 py-1 bg-yellow-500/20 rounded-full mb-6">
                <span className="w-2 h-2 bg-yellow-400 rounded-full mr-2"></span>
                <span className="text-yellow-400 text-sm font-medium">WHY VIBESEC</span>
              </div>
              
              <h2 className="text-4xl font-bold mb-6">
                Transformative Solutions{" "}
                <span className="text-gray-400">Across the Spectrum</span>
              </h2>
              
              <div className="space-y-6">
                <div className="shine-effect rounded-2xl p-6 border border-gray-600">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center">
                      <img 
                        src="/lovable-uploads/9aceed14-4908-45d1-bc75-552d322be516.png" 
                        alt="Connect GitHub Repo" 
                        className="w-8 h-8 object-contain"
                      />
                    </div>
                    <h4 className="text-lg font-semibold">Connect Your GitHub Repo</h4>
                  </div>
                  <p className="text-gray-400">
                    Securely connect your public or private GitHub repository in seconds.
                  </p>
                </div>

                <div className="shine-effect rounded-2xl p-6 border border-gray-600">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center">
                      <img 
                        src="/lovable-uploads/cf62f380-5dd2-43cf-aa3c-761e83390015.png" 
                        alt="AI-Powered Scan" 
                        className="w-8 h-8 object-contain"
                      />
                    </div>
                    <h4 className="text-lg font-semibold">Run an AI-Powered Scan</h4>
                  </div>
                  <p className="text-gray-400">
                    Our AI scans your codebase for security risks, bad practices, and known vulnerabilities.
                  </p>
                </div>

                <div className="shine-effect rounded-2xl p-6 border border-gray-600">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center">
                      <img 
                        src="/lovable-uploads/9a8d1cf3-a4f5-4378-b1ce-e8ec17af0e78.png" 
                        alt="Security Report" 
                        className="w-8 h-8 object-contain"
                      />
                    </div>
                    <h4 className="text-lg font-semibold">Get a Downloadable Security Report</h4>
                  </div>
                  <p className="text-gray-400">
                    Receive a detailed, actionable vulnerability report generated by AI.
                  </p>
                </div>

                <div className="shine-effect rounded-2xl p-6 border border-gray-600">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center">
                      <img 
                        src="/lovable-uploads/8bca81bc-29b8-4cec-ac92-690b15f98f9f.png" 
                        alt="One-Click Fix" 
                        className="w-8 h-8 object-contain"
                      />
                    </div>
                    <h4 className="text-lg font-semibold">FUTURE: One-Click Fix (Pro Tier)</h4>
                  </div>
                  <p className="text-gray-400">
                    Upgrade to VibeSec Pro and automatically patch common vulnerabilities with a single click.
                  </p>
                </div>
              </div>
            </div>

            <div className="relative">
              <div className="bg-black rounded-2xl p-8">
                <div className="aspect-square bg-black rounded-lg flex items-center justify-center relative overflow-hidden">
                  <img 
                    src="/lovable-uploads/26ea5041-8925-4176-b641-dba8fa534fa7.png" 
                    alt="Transformative Solutions"
                    className="w-full h-full object-cover rounded-lg grayscale brightness-110 contrast-125 saturate-0 filter drop-shadow-[0_0_20px_rgba(255,255,255,0.3)]"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Features;
